### ISSUE TITLE
unkown Error

### ISSUE THREAD

**Issue by p-k-l** [mit-ll/DL-YouTube-CC#1]
killum@killum:~/Desktop/PSIAP-DL-YouTube-CC-master$ su
Password: 
(base) root@killum:/home/killum/Desktop/PSIAP-DL-YouTube-CC-master# conda activate ytdl
(ytdl) root@killum:/home/killum/Desktop/PSIAP-DL-YouTube-CC-master# python3 get_vids.py
usage: get_vids.py [-h] -c CHANNELID [-f FILEPATH] [-w] [-a] [-v] [-d]
get_vids.py: error: the following arguments are required: -c/--channelid
(ytdl) root@killum:/home/killum/Desktop/PSIAP-DL-YouTube-CC-master#  python3  get_vids.py  -c UCu0wUIWkOXUJrAzXB4IksAQ -f /home/killum/upload/  -w  -a 
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=833011435577-36644vb6ljhbjo2ftlrog9kl3dk65m2c.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.force-ssl&state=PHtH0kiyVziWYcu4nBgyERHzMZfpOT&prompt=consent&access_type=offline
Enter the authorization code: 4/3gGTL6y4NUrCIOQLI5jIoHDqHRh02xiTZlvw2PaRfWPhO21rPhVSUM0
[youtube] ASLgbbMmF1M: Downloading webpage
[youtube] ASLgbbMmF1M: Downloading video info webpage
ERROR: ASLgbbMmF1M: YouTube said: Invalid parameters.
ERROR: ASLgbbMmF1M: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=ASLgbbMmF1M
[youtube] YTD3oeR9_PE: Downloading webpage
[youtube] YTD3oeR9_PE: Downloading video info webpage
ERROR: YTD3oeR9_PE: YouTube said: Invalid parameters.
ERROR: YTD3oeR9_PE: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=YTD3oeR9_PE
[youtube] 1N-9SUGTs1o: Downloading webpage
[youtube] 1N-9SUGTs1o: Downloading video info webpage
ERROR: 1N-9SUGTs1o: YouTube said: Invalid parameters.
ERROR: 1N-9SUGTs1o: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=1N-9SUGTs1o
[youtube] GcprxjbU5Yg: Downloading webpage
[youtube] GcprxjbU5Yg: Downloading video info webpage
ERROR: GcprxjbU5Yg: YouTube said: Invalid parameters.
ERROR: GcprxjbU5Yg: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=GcprxjbU5Yg
[youtube] UYBrzSN9CX8: Downloading webpage
[youtube] UYBrzSN9CX8: Downloading video info webpage
ERROR: UYBrzSN9CX8: YouTube said: Invalid parameters.
ERROR: UYBrzSN9CX8: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=UYBrzSN9CX8
[youtube] 7BAxfj3Hi0A: Downloading webpage
[youtube] 7BAxfj3Hi0A: Downloading video info webpage
ERROR: 7BAxfj3Hi0A: YouTube said: Invalid parameters.
ERROR: 7BAxfj3Hi0A: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=7BAxfj3Hi0A
[youtube] YDQkr0kJBaM: Downloading webpage
[youtube] YDQkr0kJBaM: Downloading video info webpage
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR: YDQkr0kJBaM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: YDQkr0kJBaM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. raised for https://www.youtube.com/watch?v=YDQkr0kJBaM
[youtube] U-0SjOs6AnM: Downloading webpage
[youtube] U-0SjOs6AnM: Downloading video info webpage
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR: U-0SjOs6AnM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: U-0SjOs6AnM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. raised for https://www.youtube.com/watch?v=U-0SjOs6AnM
[youtube] hoMpE5gu-NQ: Downloading webpage
[youtube] hoMpE5gu-NQ: Downloading video info webpage
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR: hoMpE5gu-NQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: hoMpE5gu-NQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. raised for https://www.youtube.com/watch?v=hoMpE5gu-NQ
[youtube] K2MzPCfhQ74: Downloading webpage
[youtube] K2MzPCfhQ74: Downloading video info webpage
ERROR: K2MzPCfhQ74: YouTube said: Invalid parameters.
ERROR: K2MzPCfhQ74: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=K2MzPCfhQ74
[youtube] P5iGCj-Tlj0: Downloading webpage
[youtube] P5iGCj-Tlj0: Downloading video info webpage
ERROR: P5iGCj-Tlj0: YouTube said: Invalid parameters.
ERROR: P5iGCj-Tlj0: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=P5iGCj-Tlj0
[youtube] mF7dcffCLfg: Downloading webpage
[youtube] mF7dcffCLfg: Downloading video info webpage
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR: mF7dcffCLfg: YouTube said: Invalid parameters.
ERROR: mF7dcffCLfg: YouTube said: Invalid parameters. raised for https://www.youtube.com/watch?v=mF7dcffCLfg
(ytdl) root@killum:/home/killum/Desktop/PSIAP-DL-YouTube-CC-master#

**Comment by p-k-l** [comment]
if you have this error update your youtube-dl 
pip install youtube-dl -U

**Comment by aweinert-MIT** [comment]
Do you have a pip `installation.txt` that could be added to this repo?
